# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/koungkub/soa2019_group8
    branches:
      only:
        - master
    steps:
      - checkout:
        path: ~/parking

      - run: pwd
      - run: ls -la
      - run: go mod download
      - run: go test -v ./...
