# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
    build:
        docker:
            - image: circleci/golang:1.12
        environment:
            CGO_ENABLED: 0
            GOOS: linux
        working_directory: ~/soa2019_group8/parking
        branches:
            only:
                - master
        steps:
            - checkout:
                path: ~/soa2019_group8
            - restore_cache:
                keys:
                    - pkg-cache-{{ arch }}-{{ checksum "go.mod" }}
                    - pkd-cache
            - run:
                name: check dependencies and download dependencies
                command: |
                    go mod tidy
                    go mod download
            - run:
                name: vendor a dependencies
                command: |
                    go mod vendor
            - save_cache:
                key: pkg-cache-{{ arch }}-{{ checksum "go.mod" }}
                paths:
                    - /go/pkg
            - run:
                name: run test
                command: |
                    go test -v ./...
            - run:
                name: build code
                command: |
                    go build -a -tags netgo -ldflags '-w' -o app -mod=vendor .
                        