version: '3'

services: 
  parking:
    build:
      context: ../parking
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    environment: 
      - APP_ENV=production
      - PORT=:8080
      - DB_USERNAME=parking
      - DB_PASSWORD=P@ssw0rd
      - DB_HOST=mysql-parking
      - DB_PORT=3306
      - DB_DATABASE=Park
      - SECRET_KEY=ilovedog
      - DISCOUNT_SERVICE_URL=http://discount:9090
      - DISCOUNT_SERVICE_PATH=/parking/discount
      - LOGSTASH=logstash:5044
      - EUREKA=http://eureka:8761/eureka
    networks: 
      - 'soa'
    depends_on: 
      - mysql-parking
      - logstash

  discount:
    build:
      context: ../discount
      dockerfile: Dockerfile
    ports: 
      - 9090:9090
    environment: 
      - APP_ENV=production
      - PORT=:9090
      - SECRET_KEY=ilovedog
      - DB_USERNAME=discount
      - DB_PASSWORD=P@ssw0rd
      - DB_HOST=mysql-discount
      - DB_PORT=3306
      - DB_DATABASE=Discount
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DATABASE=0
      - LOGSTASH=logstash:5044
      - EUREKA=http://eureka:8761/eureka
    networks: 
      - 'soa'
    depends_on: 
      - mysql-discount
      - logstash
      - redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    ports: 
      - 9200:9200
      - 9300:9300
    environment: 
      - discovery.type=single-node
    networks: 
      - 'soa'

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    ports: 
      - 5601:5601
    networks: 
      - 'soa'
    depends_on: 
      - elasticsearch

  logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile
    ports:
      - 5044:5044
      - 9600:9600
    networks: 
      - 'soa'
    depends_on: 
      - elasticsearch

  mysql-parking:
    image: mysql:5.7
    ports: 
      - 3306:3306
    environment: 
      - TZ=Asia/Bangkok
      - MYSQL_USER=parking
      - MYSQL_DATABASE=Park
      - MYSQL_PASSWORD=P@ssw0rd
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PORT=3306
    networks: 
      - 'soa'

  mysql-discount:
    image: mysql:5.7
    ports: 
      - 3307:3306
    environment: 
      - TZ=Asia/Bangkok
      - MYSQL_USER=discount
      - MYSQL_DATABASE=Discount
      - MYSQL_PASSWORD=P@ssw0rd
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PORT=3306
    networks: 
      - 'soa'
  
  redis:
    image: redis:5-alpine
    ports: 
      - 6379:6379
    environment: 
      - TZ=Asia/Bangkok
    networks: 
      - 'soa'

  eureka:
    image: springcloud/eureka
    ports: 
      - 8761:8761
    networks: 
      - 'soa'

  gateway:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - 1323:1323
    depends_on: 
      - discount
      - parking
    networks:
      - 'soa'

networks: 
  soa:
    driver: bridge
